config/routes.rb
Rails.application.routes.draw do
   # static pages
   as :static_pages do
      root to: 'pages#home'
      get 'family_page', to: 'pages#family'
      get 'care_giver_page', to: 'pages#care_giver'
      post 'contact', to: 'pages#create', as: :create_message
   end
   # devise for our two users
   devise_for :families, path: 'families', controllers: { sessions: "families/sessions", confirmations: 'families/confirmations', registrations: 'families/registrations'}
   devise_for :care_givers, path: 'care_givers' , controllers: { sessions: "caregivers/sessions", confirmations: 'caregivers/confirmations', registrations: 'caregivers/registrations'}
   # resources
   resources :job_posts
   resources :family_steps
   resources :care_giver_steps
   resources :charges
   # resources :states, only: :new
   devise_scope :family do
      get 'states', to: 'families/registrations#city'
   end
   devise_scope :care_giver do
      get 'states', to: 'caregivers/registrations#city'
   end
   # family steps recipient
   post 'family_steps/recipient_information', to: 'family_steps#create'
   post 'family_steps/recipient_information_second', to: 'family_steps#care_needs'
   post 'family_steps/recipient_information_third', to: 'family_steps#mobility_quality'
   post 'family_steps/recipient_information_fourth', to: 'family_steps#conditions'
   # caregiver steps
   post 'care_giver_steps/skills_information', to: 'care_giver_steps#skills_information'
   post 'care_giver_steps/disease_management', to: 'care_giver_steps#conditions'
   post 'care_giver_steps/yes_no', to: 'care_giver_steps#yes_no'
   post 'care_giver_steps/personal_statement', to: 'care_giver_steps#personal_statement'
   post 'care_giver_steps/experience', to: 'care_giver_steps#experience'
   get 'states-cg', to: 'care_giver_steps#city'
   # family dashboard
   as :family do
      get 'family', to: 'family#index', as: :family_root
      get 'family/new_post', to: 'family#new_post'
      post 'family/create_post', to: 'family#create_post'
      post 'family/update_recipient_for_post', to: 'family#update_recipient_for_post'
      get 'family/my_posting', to: 'family#my_posting', as: :my_posting
      delete 'family/my_posting/delete/:id', to: 'family#delete_post', as: :delete_post
      get 'family/edit_posting', to: 'family#edit_posting', as: :edit_posting
      post 'family/update_post', to: 'family#update_post'
      get 'family/recipient', to: 'family#recipient'
      get 'family/edit_recipient/:id/edit', to: 'family#edit_recipient'
      patch 'family/update_recipient/:id', to: 'family#update_recipient'
      get 'family/team_search', to: 'family#team_search', as: :search_team
      get 'family/team_search_results', to: 'family#team_search_results', as: :search_team_results
      get 'family/team_search_results_state', to: 'family#team_search_results_state', as: :search_team_results_state
      get 'family/team_search_results_city', to: 'family#team_search_results_city', as: :search_team_results_city
      get 'family/team/:id', to: 'family#team_show', as: :team_show
      get 'family/team_member/:id', to: 'family#team_show_member', as: :team_show_member
      get 'family/team_selection/:id', to: 'family#team_selection', as: :team_selection
      get 'family/my_team/:id', to: 'family#my_team', as: :my_team
      patch 'family/remove_team', to: 'family#remove_team', as: :remove_team
   end
   # caregiver dashboard
   as :team do
      get 'team', to: 'team#index', as: :team_root
      get 'team/posts/:id', to: 'team#all_posts', as: :all_posts
      get 'team/my_team/:id', to: 'team#my_team', as: :my_care_team
      get 'team/remove_member/:id', to: 'team#remove_member', as: :remove_member
      get 'team/new_team', to: 'team#new_team'
      post 'team/create_team', to: 'team#create_team'
      get 'team/join_team', to: 'team#join_team', as: :join_teams
      get 'team/search_results', to: 'team#search_results', as: :team_results
      get 'team/search_results_state', to: 'team#search_results_state', as: :team_results_state
      get 'team/search_results_city', to: 'team#search_results_city', as: :team_results_city
      get 'team/edit_post/:id/edit', to: 'team#edit_post'
      patch 'team/edit_post/:id/update_post', to: 'team#update_post'
      get 'team/show_team/:id', to: 'team#show_team', as: :show_team
      get 'team/team_member/:id', to: 'team#show_member', as: :show_member
      patch '/team/update_team/:id', to: 'team#update_team'
      get 'team/hours/:id', to: 'team#hours', as: :care_hours
      post 'team/create_hours/:id', to: 'team#create_hours', as: :create_hours
      get 'team/leader_hours/:id', to: 'team#leader_hours', as: :leader_hours 
      get 'team/care_giver_hours/', to: 'team#care_giver_hours', as: :care_giver_hours 
      get 'team/edit_skills', to: 'team#edit_skills', as: :edit_skills 
      post 'team/edit_skills_update', to: 'team#edit_skills_update'
      get 'team/edit_disease', to: 'team#edit_disease', as: :edit_disease 
      post 'team/edit_disease_update', to: 'team#edit_disease_update'  
      get 'team/edit_questionnaire', to: 'team#edit_questionnaire', as: :edit_questionnaire
      post 'team/edit_questionnaire_update', to: 'team#edit_questionnaire_update'    
      get 'team/edit_experience', to: 'team#edit_experience', as: :edit_experience    
      patch 'team/edit_experience_update', to: 'team#edit_experience_update'
      get 'team/edit_statement', to: 'team#edit_statement', as: :edit_statement          
      post 'team/edit_statement_update', to: 'team#edit_statement_update'      
   end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
   layout "team_dashboard" 
   before_action :authenticate_care_giver!  

   def index
      @team = current_care_giver
      @check_member = current_care_giver.care_team
      @leader = CareTeam.where(care_giver_id: current_care_giver.id)[0]
   end

   def new_team

   end

   def create_team
      @team = CareTeam.new(sanitize_team)
      if @team.save
         unless current_care_giver.care_team
            current_care_giver.update(leader: true)
            @team.update(care_giver: current_care_giver)
         end
         redirect_to team_root_path
      else
         render html: "Sorry the post wasnt updated"
      end
   end

   def join_team 
      @teams = CareTeam.all
   end

   def search_results
      @teams = CareTeam.search(params[:search]).paginate(page: params[:page],:per_page => 5)
      @all_teams = CareTeam.all.order('created_at ASC')
   end

   def search_results_city
      @teams = CareTeam.search_both(params[:city],params[:state]).paginate(page: params[:page],:per_page => 5) if params[:state].present? && params[:city].present?     
      @all_teams = CareTeam.all.order('created_at ASC')
   end

   def all_posts
      @caregiver = CareGiver.find(params[:id])
      @recent_jobs = JobPost.all.order('created_at ASC')
      @jobs_by_state = JobPost.where(public: true, state: "#{@caregiver.state}").paginate(page: params[:page],:per_page => 5)
      @Jobpost = JobPost.where(public: true, city: "#{@caregiver.city}").paginate(page: params[:page],:per_page => 2)
      @care_team_members = CareGiver.all.where(care_team: params[:id])
   end

   def edit_post
      @Jobpost = JobPost.find(params[:id]) 
      @email = @Jobpost.family.email
      @check_member = current_care_giver.care_team
      @leader = CareTeam.where(care_giver_id: current_care_giver.id)[0]
   end

   def update_post
      @Jobpost = JobPost.find(params[:id])
      if @Jobpost.update(taken: true)
         redirect_to team_posts_path, :flash => { :notice => "Awesome you have requested this job! the family will be in touch soon" }
      else
         render html: "Sorry the post wasnt updated"
      end 
   end

   def my_team
      @families = Family.where(care_team_id: params[:id]) 
      @care_team = CareTeam.find(params[:id])
      @care_team_members = CareGiver.all.where(care_team: params[:id])
      @care_givers_hours = Hour.where(care_giver_id: current_care_giver.id)  
      @companion = 0      
      @personal = 0      
      @total = 0;
      @care_givers_hours.each do |record|
         @companion += record.companion_hours
         @personal += record.personal_hours
      end
      @total = @companion + @personal
   end

   def remove_member
      @member = CareGiver.find(params[:id]);
      @leader = CareTeam.where(care_giver_id: current_care_giver.id)[0]
      @member.update(care_team: nil)
      redirect_to my_care_team_path(:id => @leader)
   end

   def show_team
      @care_team = CareTeam.find(params[:id]) 
      @care_team_members = CareGiver.all.where(care_team: params[:id]) 
   end

   def show_member
      @member = CareGiver.find(params[:id])  
      @leader = CareTeam.find_by(care_giver_id: params[:id])
      @work_exp = WorkExp.where(care_giver_id: params[:id]) 
      @certificates = Certificate.where(care_giver_id: params[:id]) 
      @education = Education.where(care_giver_id: params[:id]) 
   end

   def update_team
      @team = CareTeam.find(params[:id])
      @join_team_message = 'Thanks for selecting the team! You will hear from the team leader soon.'
      if current_care_giver.update(care_team: @team) 
         flash[:notice] = @join_team_message        
         redirect_to team_root_path
      else
         flash[:notice] = 'Sorry this team is full!'
         redirect_to show_team_path
      end
   end

   def hours
      @family = Family.find(params[:id])
   end

   def leader_hours
      beginning_of_week = Time.current.beginning_of_week
      end_of_week = beginning_of_week.end_of_week
      @job_post = JobPost.find(params[:id])
      @hours = Hour.where(job_post_id:  @job_post.id, created_at: beginning_of_week..end_of_week)
      @companion = 0
      @personal = 0
      @hours.each do |record|
         @companion += record.companion_hours
         @personal += record.personal_hours
      end
      @total
      @care_team = CareTeam.find_by(care_giver_id: current_care_giver.id)
      if @care_team == nil
         @total = "Once you connect with a team you will be able to confirm the teams hours worked on a weekly basis"
      else
         @total = (@companion * @care_team.companion_hrly_price) + (@personal * @care_team.personal_hrly_price)
      end
   end

   def care_giver_hours
      beginning_of_week = Time.current.beginning_of_week
      end_of_week = beginning_of_week.end_of_week
      @hours = Hour.where(care_giver_id:  current_care_giver.id, created_at: beginning_of_week..end_of_week)
      @companion = 0
      @personal = 0
      @hours.each do |record|
         @companion += record.companion_hours
         @personal += record.personal_hours
      end
      @total
      @care_team = current_care_giver.care_team
      @total = (@companion * @care_team.companion_hrly_price) + (@personal * @care_team.personal_hrly_price)
   end

   def for_the_day(x, y)
      if Hour.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now), :job_post_id => x, :care_giver_id => y).any? == true         
         return "Exceeds daily limit"
      end
   end

   def create_hours
      @family = Family.find(params[:id])      
      @check = self.for_the_day(@family.job_post.id, current_care_giver.id)
      if @check 
         flash[:notice] =  "You have already logged Your hours for today."
         redirect_to controller: 'team', action: 'hours', id: @family.id  
      else 
         @hours = current_care_giver.hours.create(sanitize_hours)
         @hours.update(job_post_id: @family.job_post.id)
         if @hours.save
            flash[:notice] = "Your hours have been successfully logged."
            redirect_to controller: 'team', action: 'hours', id: @family.id 
         end 
      end
   end

   def edit_skills

   end

   def edit_skills_update        
      @team = current_care_giver
      @team.update(companion_care: params[:companion_care])
      @team.update(personal_care: params[:personal_care])  
      @team.update(languages: params[:languages]) 
      redirect_to "/care_givers/edit" 
      flash[:notice] = "Your profile has been successfully updated."      
   end

   def edit_disease

   end


   def edit_disease_update   
      @team = current_care_giver
      if params[:conditions].last == ""
         params[:conditions].pop
      end
      @team.update(conditions: params[:conditions]) 
      @team.update(related_service: params[:related_service])       
      redirect_to "/care_givers/edit" 
      flash[:notice] = "Your profile has been successfully updated."  
   end

   def edit_questionnaire

   end

   def edit_questionnaire_update
      @team = current_care_giver
      @team.update_attributes(sanitize_care_giver) 
      redirect_to "/care_givers/edit" 
      flash[:notice] = "Your profile has been successfully updated."  
   end

   def edit_experience
      @team = current_care_giver
   end
   
   def edit_experience_update
      current_care_giver.update(sanitize_exp)
      if !params[:certificates][:school_program].empty? && !params[:certificates][:certificate].empty? &&
         !params[:certificates][:certificatid].empty? && !params[:certificates][:state].empty? &&
         !params[:certificates][:from].empty? && !params[:certificates][:to].empty?
         if current_care_giver.certificate
           @cert =  current_care_giver.certificate.update(sanitize_certificates)
         else
            @cert = current_care_giver.create_certificate(sanitize_certificates)
            @cert.save            
         end 
      end 
      redirect_to "/care_givers/edit" 
      flash[:notice] = "Your profile has been successfully updated." 
   end

   def edit_statement

   end

   def edit_statement_update        
      @team = current_care_giver
      @team.update_attributes(sanitize_care_giver)       
      redirect_to "/care_givers/edit" 
      flash[:notice] = "Your profile has been successfully updated."      
   end

   private 
      def sanitize_team
         params.require(:care_team).permit(:team_name, :team_statement, :team_state, :team_city, :personal_hrly_price, :companion_hrly_price)
      end

      def sanitize_care_giver
         params.require(:care_giver).permit(:dependable_car, :physical_issues, :tb_malaria, :smoke, :smoke_several_hours, :drugs_alcohol, :felonies, :years_experience, :statement, :authorized)
      end

      def sanitize_exp
         params.require(:care_giver).permit( work_exps_attributes: [:id, :employer, :title, :state, :city, :from, :to], educations_attributes: [:id, :school, :major, :state, :city, :from, :to])         
      end

      def sanitize_certificates
         params.require(:certificates).permit(:school_program,:certificate,:certificatid,:state,:from,:to)
      end

      def sanitize_hours
         params.require(:hours).permit(:day_worked, :companion_hours, :personal_hours)         
      end
end

app/controllers/teams/confirmations_controller.rb
# frozen_string_literal: true

class Teams::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
      def after_confirmation_path_for(resource_name, resource)
         sign_in(resource)               
         team_root_path
      end
end

app/controllers/teams/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Teams::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/teams/passwords_controller.rb
# frozen_string_literal: true

class Teams::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/teams/sessions_controller.rb
# frozen_string_literal: true

class Teams::SessionsController < Devise::SessionsController
   include Accessible
   skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/team/edit_statement.html.erb
<div class="signup-container-cg">
   <h2 class="signup-container__signup-text">Edit Personal Statement</h2>
   <%= form_for :care_giver, url: 'edit_statement_update',  html: {style: "height: 1000px"} do |f| %>
      <div class="signup-input-container-cg">
         <h3 class="conditions-container__companion--text">Personal Statement a brief description of why the families want to hire you</h3>
         <%= f.text_area :statement, maxlength: 1000, placeholder: "Use a story and make it personal", required: true, class: "statement", value: current_care_giver.statement %><br>
         <%= f.submit "Update", class: "signup-input-container-cg--submit-cg"%>
      </div>
   <% end %>
</div>

app/views/team/my_team.html.erb
<div class="team-container" style="background: #F3FCFF">
   <div class="home-teamsearch-container__care-text">
      <h3 class="home-teamsearch-container__care-text--text"><%= @care_team.team_name %></h3>
   </div>
   <div class="team-container__data-container" style="padding: 1.5rem 0">
      <div class="team-container__data-container__top">
         <p style="font-size: 1.35rem; margin-bottom: 0rem;">Team Statement</p>
         <p style="font-size: 1.15rem; color: grey;"><%= @care_team.team_statement %></p>
         <p class="member-text" style="display: inline">Leader: <%= @care_team.care_giver.firstname%></p>
         <%= link_to 'View Leader', show_member_path(:id => @care_team.care_giver.id), class: "view-text" %><br>
         <% if current_care_giver.care_team %>
            <% @care_team_members.each do |person| %>
               <div style="margin: 1rem 0">
                  <p class="member-text" style="display: inline">Member: <%= person.firstname %></p>
                  <%= link_to 'View', show_member_path(:id => person.id), class: "view-text" %>
               </div>
            <% end %>
         <% else %>
            <% @care_team_members.each do |person| %>
               <div style="margin: 1rem 0">
                  <p class="member-text" style="display: inline">Member: <%= person.firstname %></p>
                  <%= link_to "Remove", remove_member_path(:id => person.id), :data => {:confirm=>'Are you sure?'}, class: "view-text" %>
                  <%= link_to 'View', show_member_path(:id => person.id), class: "view-text" %>
               </div>
            <% end %>
         <% end %>
      </div>
      <div class="team-container__data-container__bottom">
         <p class="service-text">Companion Care: $<%= @care_team.companion_hrly_price %> per hour</p>
         <p class="service-text">Personal Care: $<%= @care_team.personal_hrly_price %> per hour</p>
         <p class="service-text">Your total hours worked: <%= @total %></p>
         <p id="customer-button" class="customer-service">Customer Service</p>
         <a class="service-text" id="service-number" style="display: none;" href="tel:+1-800-888-8888">tel:+1-800-888-8888</a>
      </div>
   </div>
</div>
<% if @families.length == 0 %>
   <div class="all-posts-container">
      <div class="home-teamsearch-container__care-text">
         <h3 class="home-teamsearch-container__care-text--text">You are currently not working with any families</h3>
      </div>
      <div class="jobs-container">
            <div class="jobs-container__job">
               <div class="jobs-container__job-data"></div>
            </div>
      </div>
   </div>
 <% else %>
    <div class="all-posts-container">
      <div class="home-teamsearch-container__care-text">
         <h3 class="home-teamsearch-container__care-text--text">Your Jobs</h3>
      </div>
      <div class="jobs-container">
         <% @families.reverse.each do |family|%>
            <div class="jobs-container__job">
               <div class="jobs-container__job-data">
                  <h2 style="color: #133A6B">Contact: <%= family.firstname.titleize %> <%= family.lastname.first.titleize %>.</h2>
                  <a class="jobs-container__job-data--text" href="tel:<%= family.phone %>">Phone: <%= family.phone %></a>
                  <% if family.recipient %>
                     <h4 class="jobs-container__job-data--text">Care Recipient: <%= family.recipient.firstname %>, <%= family.recipient.gender %>, <%= family.recipient.age %> years old</h4>
                     <h4 class="jobs-container__job-data--text">Location: <%= family.recipient.city %>, <%= family.recipient.state %></h4>
                  <% end %>
                  <% if current_care_giver.care_team_id == nil %>
                     <%= link_to "Your Teams Hours for this Week", leader_hours_path(:id => family.job_post.id), class: "jobs-container__job-data--text", style: "margin: 15px auto; display: block;" %>
                  <% else %>
                     <%= link_to "Your Hours for this Week", care_giver_hours_path, class: "jobs-container__job-data--text", style: "margin: 15px auto; display: block;" %>
                  <% end %>
               </div>
               <%= link_to "Log Hours", care_hours_path(:id => family.id), class: "request-job-button" %>
            </div>
         <% end %>
      </div>
    </div>
 <% end %>

app/views/team/search_results.html.erb
<% if @teams.length > 0 %>
   <div class="search-results-container">
      <div class="home-teamsearch-container__care-text">
         <h3 class="home-teamsearch-container__care-text--text">Care teams</h3>
      </div>
      <h3 style="text-align: center; color: #104A75; font-size: 1.2rem;">Below are the teams best matched on your search</h3>
      <div class="teams-container">
         <% @teams.each do |team| %>
            <div class="teams-container__team">
               <div class="teams-container__data">
                  <h3><%= team.team_name %></h3>
                  <div class="teams-container__data--location-hours">
                     <h3><%= team.team_city%>, <%= team.team_state %></h3>
                     <h3>$<%= team.companion_hrly_price %>-$<%= team.personal_hrly_price %>/hr<h3p>
                  </div>
                  <p class="preview"><%= team.team_statement %></p>
               </div>
               <a class="contact-team-button" href="/team/show_team/<%= team.id %>">View team</a>
            </div>
         <% end %>
      </div>
      <div class="digg_pagination" style="margin-bottom: 1rem; display: flex; justify-content: center;">
         <%= will_paginate @teams %>
      </div>
   </div>
   <%= link_to 'back to search teams', join_teams_path, class: "home-jobpost-container__button", style: "width: 250px; text-decoration: none; text-align: center;" %>
<% else %>
   <div class="search-results-container">
      <div class="home-teamsearch-container__care-text">
         <h3 class="home-teamsearch-container__care-text--text">Care teams</h3>
      </div>
      <h3 style="text-align: center; color: #104A75; font-size: 1.2rem;">There are no teams containing the term(s) <%= params[:search] %>.</h3>
      <div class="teams-container">
         <%= link_to 'back to search teams', join_teams_path, class: "home-jobpost-container__button", style: "width: 250px; text-decoration: none; text-align: center;" %>
      </div>
   </div>
<% end %> 

app/views/team/search_results_city.html.erb
<% if @teams.length > 0 %>
   <div class="search-results-container">
      <div class="home-teamsearch-container__care-text">
         <h3 class="home-teamsearch-container__care-text--text">Care Teams</h3>
      </div>
      <h3 style="text-align: center; color: #104A75; font-size: 1.2rem;">Below are the teams best matched to your search</h3>
      <div class="teams-container">
         <% @teams.each do |team| %>
            <div class="teams-container__team">
               <div class="teams-container__data">
                  <h3><%= team.team_name %></h3>
                  <div class="teams-container__data--location-hours">
                     <h3><%= team.team_city%>, <%= team.team_state %></h3>
                     <h3>$<%= team.companion_hrly_price %>-$<%= team.personal_hrly_price %>/hr<h3p>
                  </div>
                  <p class="preview"><%= team.team_statement %></p>
               </div>
               <a class="contact-team-button" href="/team/show_team/<%= team.id %>">View Team</a>
            </div>
         <% end %>
      </div>
      <div class="digg_pagination" style="margin-bottom: 1rem; display: flex; justify-content: center;">
         <%= will_paginate @teams %>
      </div>
   </div>
   <%= link_to 'back to search teams', join_teams_path, class: "home-jobpost-container__button", style: "width: 250px; text-decoration: none; text-align: center;" %>
<% else %>
   <div class="search-results-container">
      <div class="home-teamsearch-container__care-text">
         <h3 class="home-teamsearch-container__care-text--text">Care teams</h3>
      </div>
      <h3 style="text-align: center; color: #104A75; font-size: 1.2rem;">Sorry, there are no teams currently in the designated area. Please go back and revise the search location.</h3>
      <div class="teams-container">
         <%= link_to 'Back to Team Search', join_teams_path, class: "home-jobpost-container__button", style: "width: 250px; text-decoration: none; text-align: center;" %>
      </div>
   </div>
<% end %> 

app/views/team/show_team.html.erb
<p><%= flash[:notice] %></p>
<div class="team-container">
   <div class="home-teamsearch-container__care-text">
      <h3 class="home-teamsearch-container__care-text--text"><%= @care_team.team_name %></h3>
   </div>
   <div class="team-container__data-container">
      <div class="team-container__data-container__top">
         <p style="font-size: 1.35rem; margin-bottom: 0rem;">Team statement</p>
         <p style="font-size: 1.15rem; color: grey;"><%= @care_team.team_statement %></p>
         <p class="member-text" style="display: inline">Leader: <%= @care_team.care_giver.firstname%></p>
         <%= link_to 'View Leader', show_member_path(:id => @care_team.care_giver.id), class: "view-text" %><br>
         <% @care_team_members.each do |person| %>
            <div style="margin: 1rem 0">
               <p class="member-text" style="display: inline">Member: <%= person.firstname %></p>
               <%= link_to 'View Member', show_member_path(:id => person.id), class: "view-text" %>
            </div>
         <% end %>
         <% unless current_care_giver.care_team_id %>
             <%= form_for current_care_giver, url: {action:'update_team'},  html: {class: "nifty_form"} do |f| %>
               <%= f.submit 'Join Team', :data => { :confirm => 'Are you sure?' }, class: "select-team-button" %>
            <% end %>
         <% end %>
      </div>
      <div class="team-container__data-container__bottom">
         <p class="service-text">Companion Care $<%= @care_team.companion_hrly_price %> per hour</p>
         <p class="service-text">Personal Care $<%= @care_team.personal_hrly_price %> per hour</p>
         <p class="service-text">Team Leader contact: <%= @care_team.care_giver.phone %></p>
         <p class="service-text">You can click "Join This Team" or contact the team leader</p>
         <a class="customer-service" href="tel:+<%= @care_team.care_giver.phone %>">Contact Team Leader</a>
         <!--<a class="service-text" id="service-number" style="display: none; text-decoration: none;" href="tel:+1-800-888-8888">+1-800-888-8888</a>-->
      </div>
   </div>
</div>

app/views/team/team.html.erb
<h3>Your Team</h3>
<div style="border: 1px solid lightgrey" class="post">
   <p>Team name: <%= @team.team_name %></p>
   <p>Team statement: <%= @team.team_statement %></p>
</div>
<p>user will also be able to see all members of the team and also leader</p>