config/routes.rb
Rails.application.routes.draw do
   # static pages
   as :static_pages do
      root to: 'pages#home'
      get 'family_page', to: 'pages#family'
      get 'care_giver_page', to: 'pages#care_giver'
      post 'contact', to: 'pages#create', as: :create_message
   end
   # devise for our two users
   devise_for :families, path: 'families', controllers: { sessions: "families/sessions", confirmations: 'families/confirmations', registrations: 'families/registrations'}
   devise_for :care_givers, path: 'care_givers' , controllers: { sessions: "caregivers/sessions", confirmations: 'caregivers/confirmations', registrations: 'caregivers/registrations'}
   # resources
   resources :job_posts
   resources :family_steps
   resources :care_giver_steps
   resources :charges
   # resources :states, only: :new
   devise_scope :family do
      get 'states', to: 'families/registrations#city'
   end
   devise_scope :care_giver do
      get 'states', to: 'caregivers/registrations#city'
   end
   # family steps recipient
   post 'family_steps/recipient_information', to: 'family_steps#create'
   post 'family_steps/recipient_information_second', to: 'family_steps#care_needs'
   post 'family_steps/recipient_information_third', to: 'family_steps#mobility_quality'
   post 'family_steps/recipient_information_fourth', to: 'family_steps#conditions'
   # caregiver steps
   post 'care_giver_steps/skills_information', to: 'care_giver_steps#skills_information'
   post 'care_giver_steps/disease_management', to: 'care_giver_steps#conditions'
   post 'care_giver_steps/yes_no', to: 'care_giver_steps#yes_no'
   post 'care_giver_steps/personal_statement', to: 'care_giver_steps#personal_statement'
   post 'care_giver_steps/experience', to: 'care_giver_steps#experience'
   get 'states-cg', to: 'care_giver_steps#city'
   # family dashboard
   as :family do
      get 'family', to: 'family#index', as: :family_root
      get 'family/new_post', to: 'family#new_post'
      post 'family/create_post', to: 'family#create_post'
      post 'family/update_recipient_for_post', to: 'family#update_recipient_for_post'
      get 'family/my_posting', to: 'family#my_posting', as: :my_posting
      delete 'family/my_posting/delete/:id', to: 'family#delete_post', as: :delete_post
      get 'family/edit_posting', to: 'family#edit_posting', as: :edit_posting
      post 'family/update_post', to: 'family#update_post'
      get 'family/recipient', to: 'family#recipient'
      get 'family/edit_recipient/:id/edit', to: 'family#edit_recipient'
      patch 'family/update_recipient/:id', to: 'family#update_recipient'
      get 'family/team_search', to: 'family#team_search', as: :search_team
      get 'family/team_search_results', to: 'family#team_search_results', as: :search_team_results
      get 'family/team_search_results_state', to: 'family#team_search_results_state', as: :search_team_results_state
      get 'family/team_search_results_city', to: 'family#team_search_results_city', as: :search_team_results_city
      get 'family/team/:id', to: 'family#team_show', as: :team_show
      get 'family/team_member/:id', to: 'family#team_show_member', as: :team_show_member
      get 'family/team_selection/:id', to: 'family#team_selection', as: :team_selection
      get 'family/my_team/:id', to: 'family#my_team', as: :my_team
      patch 'family/remove_team', to: 'family#remove_team', as: :remove_team
   end
   # caregiver dashboard
   as :team do
      get 'team', to: 'team#index', as: :team_root
      get 'team/posts/:id', to: 'team#all_posts', as: :all_posts
      get 'team/my_team/:id', to: 'team#my_team', as: :my_care_team
      get 'team/remove_member/:id', to: 'team#remove_member', as: :remove_member
      get 'team/new_team', to: 'team#new_team'
      post 'team/create_team', to: 'team#create_team'
      get 'team/join_team', to: 'team#join_team', as: :join_teams
      get 'team/search_results', to: 'team#search_results', as: :team_results
      get 'team/search_results_state', to: 'team#search_results_state', as: :team_results_state
      get 'team/search_results_city', to: 'team#search_results_city', as: :team_results_city
      get 'team/edit_post/:id/edit', to: 'team#edit_post'
      patch 'team/edit_post/:id/update_post', to: 'team#update_post'
      get 'team/show_team/:id', to: 'team#show_team', as: :show_team
      get 'team/team_member/:id', to: 'team#show_member', as: :show_member
      patch '/team/update_team/:id', to: 'team#update_team'
      get 'team/hours/:id', to: 'team#hours', as: :care_hours
      post 'team/create_hours/:id', to: 'team#create_hours', as: :create_hours
      get 'team/leader_hours/:id', to: 'team#leader_hours', as: :leader_hours 
      get 'team/care_giver_hours/', to: 'team#care_giver_hours', as: :care_giver_hours 
      get 'team/edit_skills', to: 'team#edit_skills', as: :edit_skills 
      post 'team/edit_skills_update', to: 'team#edit_skills_update'
      get 'team/edit_disease', to: 'team#edit_disease', as: :edit_disease 
      post 'team/edit_disease_update', to: 'team#edit_disease_update'  
      get 'team/edit_questionnaire', to: 'team#edit_questionnaire', as: :edit_questionnaire
      post 'team/edit_questionnaire_update', to: 'team#edit_questionnaire_update'    
      get 'team/edit_experience', to: 'team#edit_experience', as: :edit_experience    
      patch 'team/edit_experience_update', to: 'team#edit_experience_update'
      get 'team/edit_statement', to: 'team#edit_statement', as: :edit_statement          
      post 'team/edit_statement_update', to: 'team#edit_statement_update'      
   end
end

app/models/family.rb
class Family < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
   validates_presence_of :firstname, :lastname, :city, :phone, presence: true, on: :create
   has_one :job_post
   has_one :recipient
   has_many :care_teams
end

app/controllers/families/confirmations_controller.rb
# frozen_string_literal: true

class Families::ConfirmationsController < Devise::ConfirmationsController
#   # GET /resource/confirmation/new
  def new
    super
  end

# #   POST /resource/confirmation
  def create
    super
  end

# #   GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected
# #   The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

# #   The path used after confirmation.
   def after_confirmation_path_for(resource_name, resource)
      "/family_steps/recipient_information"  
   end
end

app/controllers/families/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Families::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/families/passwords_controller.rb
# frozen_string_literal: true

class Families::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/families/registrations_controller.rb
# frozen_string_literal: true

class Families::RegistrationsController < Devise::RegistrationsController
   include Accessible
   skip_before_action :check_user, except: [:new, :create]
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

   def new
      super 
   end

   def city
      @cities = CS.get(:us,params[:state]) 
      respond_to do |format|
         format.js { render '/families/registrations/new.js.erb' }         
         format.html { redirect_to family_steps_path } 
      end
   end

   #   POST /resource
   def create
      if verify_recaptcha
         super
       else
         build_resource(sign_up_params)
         clean_up_passwords(resource)       
         flash.now[:alert] = "There was an error with the recaptcha code below. Please re-enter the code."
         flash.delete :recaptcha_error
         render :new
       end
   end

   # GET /resource/edit
   def edit
      @state = current_family.state
      super
   end

   # PUT /resource
   def update
      super
   end

   # DELETE /resource
   def destroy
      super
   end

   # GET /resource/cancel
   # Forces the session data which is usually expired after sign
   # in to be expired now. This is useful if the user wants to
   # cancel oauth signing in/up in the middle of the process,
   # removing all OAuth session data.
   def cancel
      super
   end

   protected
      # If you have extra params to permit, append them to the sanitizer.
      def configure_sign_up_params
         devise_parameter_sanitizer.permit(:sign_up, keys:[:firstname, :middlename, :lastname, :phone, :street, :city, :state, :zip, :emergency_name, :emergency_contact, :recipient_relation, :who_pays, :heard_from])
      end

      # If you have extra params to permit, append them to the sanitizer.
      def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_updatekeys, keys:[:firstname, :middlename, :lastname, :phone, :street, :city, :state, :zip, :emergency_name, :emergency_contact, :recipient_relation])
      end

      def after_update_path_for(resource)
         "/families/edit"
      end

      #   The path used after sign up.
      def after_sign_up_path_for(resource)
         family_steps_path
      end
      # The path used after sign up for inactive accounts.
      # def after_inactive_sign_up_path_for(resource)
      #    family_steps_path      
      # end
end

app/controllers/families/sessions_controller.rb
# frozen_string_literal: true

class Families::SessionsController < Devise::SessionsController
   include Accessible
   skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/families/unlocks_controller.rb
# frozen_string_literal: true

class Families::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/family_helper.rb
module FamilyHelper
   def from
      [      
         ['Facebook', 'Facebook'],
         ['Google', 'Google'],
         ['Craigslist', 'Craigslist'],  
         ['Instagram', 'Instagram'],
         ['Youtube', 'Youtube'],
         ['Friends, Relatives or co-workers', 'Friends, Relatives or co-workers'],
         ['Billboards', 'Billboards'], 
         ['TV', 'TV'],    
         ['Newspapers', 'Newspapers'],
         ['Direct mails', 'Direct mails'],
         ['Fliers', 'Fliers'], 
         ['Yellow pages', 'Yellow pages'],         
         ['Events sponsered by TeamCarer', 'Events sponsered by TeamCarer'], 
         ['Our Employees', 'Our Employees'],
         ['Other', 'Other']       
      ]
   end
end

app/views/family/allPosts.html.erb
<% @Jobpost.each do |post| %>    <!-- Featured Post -->
   <div style="border: 1px solid lightgrey" class="post">
      <p>post title:<%= post.title %></p>
      <p>post description:<%= post.description %></p>
      <p>post created by family with id: <%= post.family_id %></p>
      <p>Is this job currently taken?: <%= post.taken %></p>
      <p>post created at: <%= post.created_at.to_formatted_s(:long) %></p>
   </div>
<% end %>

app/views/family/my_posting.html.erb
<% if !@job_post %>
   <div class="home-newpost-container">
      <div class="home-newpost-container__title-text"  style="border: none;">
         <h4 class="home-newpost-container__title-text--text">You have not made a post yet.</h4>
      </div>
   </div>
   <%= link_to "Create a post", family_root_path, class: "home-jobpost-container__button", style: "text-decoration: none; text-align: center; width: 175px;"%>
<% else %>
   <div class="home-newpost-container">
      <div class="home-newpost-container__title-text">
         <h4 class="home-newpost-container__title-text--text"><%= @job_post.title %></h4>
      </div>
      <div class="home-newpost-container__preview-container" style="padding: 2rem">
         <div class="home-newpost-container__left-side">
            <h3 class="home-newpost-container__left-side--text">Care Recipient: <%= current_family.recipient.gender %>, <%= current_family.recipient.age %> years old</h3>
            <h3 class="home-newpost-container__left-side--text">Location: <%= @job_post.city %>, <%= @job_post.state %> </h3>
            <div class="care-needed-container">
               <h3 class="home-newpost-container__left-side--text">Care Needed:</h3>
               <% if current_family.recipient.companion_care == nil && current_family.recipient.personal_care == nil %>
                  <p class="home-newpost-container__left-side--text">No Care needed</p>
               <% else %>
                  <% if current_family.recipient.companion_care == nil %>
                     <ul>
                        <% current_family.recipient.personal_care.each do |care| %>
                           <li class="home-newpost-container__left-side--text"><%= care %></li>
                        <% end %>
                     </ul>
                  <% elsif current_family.recipient.personal_care == nil %>
                     <ul>
                        <% current_family.recipient.companion_care.each do |care| %>
                           <li class="home-newpost-container__left-side--text"><%= care %></li>
                        <% end %>
                     </ul>
                  <% else %>
                     <ul>
                        <% current_family.recipient.companion_care.concat(current_family.recipient.personal_care).each do |care| %>
                           <li class="home-newpost-container__left-side--text"><%= care %></li>
                        <% end %>
                     </ul>
                  <% end %>
               <% end %>
            </div>
            <h4 class="home-newpost-container__left-side--text">Most Desired Quality: <%= current_family.recipient.quality %></h4>
            <h3 class="home-newpost-container__left-side--text">Family contact: <%= @job_post.family_contact %> </h3>
            <h3 class="home-newpost-container__left-side--text">Posted: <%= timeago(@job_post.created_at) %></h3>
         </div>
         <div class="home-newpost-container__right-side">
            <div class="medical-conditions-container">
               <h3 class="home-newpost-container__left-side--text">Medical Conditions:</h3>
               <ul>
                  <% current_family.recipient.conditions.each do |condition|%>
                     <li class="home-newpost-container__left-side--text"><%= condition %></li>
                  <% end %>
               </ul>
            </div>
            <%= link_to 'Edit Post', edit_posting_path, class: "home-jobpost-container__button", style: "width: 150px; text-align: center; text-decoration: none;"%>
         </div>
      </div>
   </div>
   <% if !current_family.care_team_id %>
      <%= link_to "Delete Post", delete_post_path(:id => current_family.job_post), :method => :delete, class: "home-jobpost-container__button", data: { confirm: "Are you sure?" }, style: "text-decoration: none; text-align: center;" %>
   <% end %>
   <% if current_family.care_team_id == nil %>
      <p class="hours-app"><%= @total %></p>
   <% else %>
      <table id="hours-table" cellspacing="0" style="margin-top: 4rem;margin-bottom: 7rem;">
         <caption class="hours-app">Hours for Week of <%= Date.today.beginning_of_week.strftime('%m/%d/%Y') %> - <%= Date.today.end_of_week.strftime('%m/%d/%Y') %></caption>
         <thead>
            <tr>
               <th class="hours-block">Caregiver</th>
               <th class="hours-block" style="border-left: none;">Day worked</th>
               <th class="hours-block" style="border-left: none;">Companion hours</th>
               <th class="hours-block" style="border-left: none;">Personal hours</th>
            </tr>
         </thead>
         <tbody>
            <% @hours.each do |hours|%>
               <tr>
                  <td class="hours-block data" scope="row" style="border-top: none;"><%= hours.care_giver.firstname.titleize %></td>
                  <td class="hours-block data" scope="row" style="border-left: none; border-top: none;"><%= hours.created_at.strftime("%m-%d-%Y") %></td>
                  <td class="hours-block data" scope="row" style="border-left: none; border-top: none;"><%= hours.companion_hours %></td>
                  <td class="hours-block data" scope="row" style="border-left: none; border-top: none;"><%= hours.personal_hours %></td>
               </tr>
            <% end %>
            <tr>
               <td style="visibility: hidden;">&nbsp;</td>
               <td style="visibility: hidden;">&nbsp;</td>
               <td class="hours-block data" style="border-top: none;">Total: <%= @companion %> hours</td>
               <td class="hours-block data" style="border-left: none; border-top: none;">Total: <%= @personal %> hours</td>
            </tr>
            <tr>
               <td style="visibility: hidden;">&nbsp;</td>
               <td style="visibility: hidden;">&nbsp;</td>
               <td class="hours-block data" style="border-top: none;">Hourly rate: $<%= @care_team.companion_hrly_price %></td>
               <td class="hours-block data" style="border-left: none; border-top: none;">Hourly rate: $<%= @care_team.personal_hrly_price %></td>
            </tr>
            <tr>
               <td style="visibility: hidden;">&nbsp;</td>
               <td style="visibility: hidden;">&nbsp;</td>
               <td style="visibility: hidden; border-right: none">&nbsp;</td>
               <td class="hours-block data" style="border-top: none; background: #104A75; color: white;">Total: <b>$<%= @total %></b></td>
            </tr>
         </tbody>
      </table>
      <%= link_to "Make Payment", new_charge_path, class: "home-jobpost-container__button", style: "text-align: center; text-decoration: none; margin-bottom: 5rem; width: 150px;" %>
   <% end %>
<% end %>

app/views/family/new.html.erb
<h3>Create a post!</h3>
<%= form_for  :Jobpost , url: {action: "create"},  html: {class: "nifty_form"} do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title %><br>
   <%= f.label :description%>
   <%= f.text_area :description, size: "40x12" %><br>
   <%= f.label :taken %>
   <%= f.select(:taken, options_for_select([['Active', true], ['Inactive', false]], :prompt => "Select")) %><br>
   <%= f.submit%>
<% end %>

app/views/family/newRecipient.html.erb
<h3>Recipient</h3>
<% if @recipient %>
   <div style="border: 1px solid lightgrey" class="post">
      <p>firstname: <%= @recipient.firstname %></p>
      <p>lastname: <%= @recipient.lastname %></p>
      <p>firstname: <%= @recipient.gender %></p>
      <p>lastname: <%= @recipient.age %></p>
      <p>Recipient Belongs to : <%= current_family.email %></p>
   </div>
   <a href="editRecipient/<%= @recipient.id %>/edit">Edit Recipient</a>
<% else %>
   <%= form_for :recipient, url: "createRecipient",  html: {class: "nifty_form"} do |f| %>
      <%= f.label :firstname %>
      <%= f.text_field :firstname, required: true %><br>
      <%= f.label :lastname %>
      <%= f.text_field :lastname, required: true %><br>
      <%= f.label :gender %>
      <%= f.text_field :gender, required: true %><br>
      <%= f.label :age %>
      <%= f.text_field :age, required: true %><br>
      <%= f.submit%>
   <% end %>
<% end %>

app/views/family/new_post.html.erb
<div class="home-newpost-container__preview-text">
   <h3 class="home-newpost-container__left-side--text" style="text-align: center; margin-top: 3rem; font-size: 1.25rem">Your job post will look like this to Teams</h3>
</div>
<div class="home-newpost-container">
   <%= form_for :jobpost , url: "update_post",  html: {class: "nifty_form"} do |f| %>
      <div class="home-newpost-container__title-text">
         <h4 class="home-newpost-container__title-text--text"><%= @jobpost_title %></h4>
      </div>
      <div class="home-newpost-container__preview-container">
         <div class="home-newpost-container__left-side">
            <h3 class="home-newpost-container__left-side--text">Care Recipient: <%= @recipient_info.gender %>, <%= @recipient_info.age %> years old</h3>
            <h3 class="home-newpost-container__left-side--text">Location: <%= @city %>, <%= @state %> </h3>
            <div class="care-needed-container">
               <h3 class="home-newpost-container__left-side--text">Care Needed:</h3>
               <% if @recipient_info.companion_care == nil && @recipient_info.personal_care == nil %>
                  <p class="home-newpost-container__left-side--text">Select Care needed</p>
               <% else %>
                  <% if @recipient_info.companion_care == nil %>
                     <ul>
                        <% @recipient_info.personal_care.each do |care| %>
                           <li class="home-newpost-container__left-side--text"><%= care %></li>
                        <% end %>
                     </ul>
                  <% elsif @recipient_info.personal_care == nil %>
                     <ul>
                        <% @recipient_info.companion_care.each do |care| %>
                           <li class="home-newpost-container__left-side--text"><%= care %></li>
                        <% end %>
                     </ul>
                  <% else %>  
                     <ul>
                        <% @recipient_info.companion_care.concat(@recipient_info.personal_care).each do |care| %>
                           <li class="home-newpost-container__left-side--text"><%= care %></li>
                        <% end %>
                     </ul>
                  <% end %>
               <% end %>
            </div>
            <h3 class="home-newpost-container__left-side--text">Most desired Quality: <%= @recipient_info.quality %> </h3>
            <h3 class="home-newpost-container__left-side--text">Family Contact: <%= @family_contact %>. </h3>
            <h3 class="home-newpost-container__left-side--text">Posted: <%= timeago(@jobpost.created_at) %></h3>
         </div>
         <div class="home-newpost-container__right-side">
            <div class="medical-conditions-container">
               <h3 class="home-newpost-container__left-side--text">Medical Conditions:</h3>
               <ul>
                  <% @recipient_info.conditions.each do |condition|%>
                     <li class="home-newpost-container__left-side--text"><%= condition %></li>
                  <% end %>
               </ul>
            </div>
         </div>
      </div>
      <%= f.text_area :companion_care, style:"display: none;", value: @care_needed  %>
      <%= f.text_area :recipient_conditions, style:"display: none;", value: @recipient_info.conditions %>
      <%= f.text_field :recipient_gender,style:"display: none;", value: @recipient_info.gender %>
      <%= f.text_field :city, style:"display: none;", value: @city %>
      <%= f.text_field :state, style:"display: none;", value: @state %>
      <%= f.text_field :family_contact, style:"display: none;", value: @family_contact %>
      <%= f.text_field :recipient_quality, style:"display: none;", value: @recipient_info.quality %>
      <div class="newpost-button-container">
         <h3 class="home-newpost-container__left-side--text" style="margin-top: 1.8rem;">Would you liked to make changes? Or continue</h3>
         <div class="button-container">
            <%= link_to 'Edit Post', edit_posting_path, class: "edit"%>
            <%= f.submit "Post", class: "post" %>
         </div>
      </div>
   <% end %>
</div>

app/views/family/teamSearch.html.erb
<h2>Search for a team!</h2>
<form>
   <input type="text" placeholder="search for a team!"/>
   <input type="button" value="search"/>
</form>

app/views/family/team_search.html.erb
<div class="home-teamsearch-container">
   <div class="home-teamsearch-container__care-text">
      <h3  class="home-teamsearch-container__care-text--text">Do you want to find a Care team?</h3>
   </div>
   <%= form_tag search_team_results_path, :method => 'get' do %>
      <div class="teamsearch-name">
         <div class="teamsearch-name__inputs">
            <%= text_field_tag :search, params[:search], placeholder: "Search Teams By name", required: true, class: "teamsearch-name__inputs--input" %>
            <%= submit_tag "Search", :name => nil, class: "teamsearch-name__inputs--button" %>
         </div>
      </div>
   <% end %>
   <p class="location-text">Or By Location</p>
   <%= form_tag search_team_results_city_path, :method => 'get' do %>
      <div class="teamsearch-name">
         <div class="teamsearch-name__inputs">
            <div style="width: 65%;">
               <%= text_field_tag :city, params[:city], placeholder: "Search Teams By city", required: true, class: "teamsearch-name__inputs--input" %>
            </div>
            <div style="width: 65%;">
               <%= select_tag :state, options_for_select(CS.states(:us).map { |code, name| [name, code] }), {:id => "state-picker", :required => true, :prompt => "State", :class => "teamsearch-name__inputs--input", :style => "height: 100%;" } %>
            </div>
            <%= submit_tag "Search", :name => nil, class: "teamsearch-name__inputs--button"  %>
         </div>
      </div>
   <% end %>
</div>

app/views/family/team_search_results.html.erb
<% if @teams.length > 0 %>
   <div class="search-results-container">
      <div class="home-teamsearch-container__care-text">
         <h3 class="home-teamsearch-container__care-text--text">Care teams</h3>
      </div>
      <h3 style="text-align: center; color: #104A75; font-size: 1.2rem;">Below are the teams best matched on your search</h3>
      <div class="teams-container">
         <% @teams.each do |team| %>
            <div class="teams-container__team">
               <div class="teams-container__data">
                  <h3><%= team.team_name %></h3>
                  <div class="teams-container__data--location-hours">
                     <h3><%= team.team_city%>, <%= team.team_state %></h3>
                     <h3>$<%= team.companion_hrly_price %>-$<%= team.personal_hrly_price %>/hr<h3p>
                  </div>
                  <p class="preview"><%= team.team_statement %></p>
               </div>
               <%= link_to 'Contact this team', team_show_path(:id => team.id), class: "contact-team-button" %>
            </div>
         <% end %>
      </div>
      <div class="digg_pagination" style="margin-bottom: 1rem; display: flex; justify-content: center;">
         <%= will_paginate @teams %>
      </div>
   </div>
   <%= link_to 'back to search teams', search_team_path, class: "home-jobpost-container__button", style: "width: 250px; text-decoration: none; text-align: center;" %>
<% else %>
   <div class="search-results-container">
      <div class="home-teamsearch-container__care-text">
         <h3 class="home-teamsearch-container__care-text--text">Care teams</h3>
      </div>
      <h3 style="text-align: center; color: #104A75; font-size: 1.2rem;">There are no teams containing the term(s) <%= params[:search] %>.</h3>
      <div class="teams-container">
         <%= link_to 'back to search teams', search_team_path, class: "home-jobpost-container__button", style: "width: 250px; text-decoration: none; text-align: center;" %>
      </div>
   </div>
<% end %> 

app/views/family/team_show.html.erb
<div class="team-container">
   <div class="home-teamsearch-container__care-text">
      <h3 class="home-teamsearch-container__care-text--text"><%= @care_team.team_name %></h3>
   </div>
   <div class="team-container__data-container">
      <div class="team-container__data-container__top">
         <p style="font-size: 1.35rem; margin-bottom: 0rem;">Team statement</p>
         <p style="font-size: 1.15rem; color: grey;"><%= @care_team.team_statement %></p>
         <p class="member-text" style="display: inline">Leader: <%= @care_team.care_giver.firstname%></p>
         <%= link_to 'View Leader', team_show_member_path(:id => @care_team.care_giver.id), class: "view-text" %><br><br>
         <% @care_team_members.each do |person| %>
            <p class="member-text" style="display: inline">Member: <%= person.firstname %></p>
            <%= link_to 'View Member', team_show_member_path(:id => person.id), class: "view-text" %><br><br>
         <% end %>
         <% unless current_family.care_team_id %>
            <% if @care_team_members.length < 1 %>
               <a href="#" class="select-team-button" id="need-more">Select This Team</a>
            <% else %>
               <%= link_to 'Select This Team',team_selection_path(:id => @care_team.id), :data => { :confirm => 'Are you sure?' }, class: "select-team-button" %>
            <% end %>
         <% else %>
            <a href="#" class="select-team-button" id="already">Select This Team</a>
         <% end %>
      </div>
      <div class="team-container__data-container__bottom">
         <p class="service-text">Companion Care $<%= @care_team.companion_hrly_price %> per hour</p>
         <p class="service-text">Personal Care $<%= @care_team.personal_hrly_price %> per hour</p>
         <p id="customer-button" class="customer-service">Customer Service</p>
         <a class="service-text" id="service-number" style="display: none;" href="tel:+1-800-888-8888">tel:+1-800-888-8888</a>
      </div>
   </div>
</div>