config/routes.rb
Rails.application.routes.draw do
   # static pages
   as :static_pages do
      root to: 'pages#home'
      get 'family_page', to: 'pages#family'
      get 'care_giver_page', to: 'pages#care_giver'
      post 'contact', to: 'pages#create', as: :create_message
   end
   # devise for our two users
   devise_for :families, path: 'families', controllers: { sessions: "families/sessions", confirmations: 'families/confirmations', registrations: 'families/registrations'}
   devise_for :care_givers, path: 'care_givers' , controllers: { sessions: "caregivers/sessions", confirmations: 'caregivers/confirmations', registrations: 'caregivers/registrations'}
   # resources
   resources :job_posts
   resources :family_steps
   resources :care_giver_steps
   resources :charges
   # resources :states, only: :new
   devise_scope :family do
      get 'states', to: 'families/registrations#city'
   end
   devise_scope :care_giver do
      get 'states', to: 'caregivers/registrations#city'
   end
   # family steps recipient
   post 'family_steps/recipient_information', to: 'family_steps#create'
   post 'family_steps/recipient_information_second', to: 'family_steps#care_needs'
   post 'family_steps/recipient_information_third', to: 'family_steps#mobility_quality'
   post 'family_steps/recipient_information_fourth', to: 'family_steps#conditions'
   # caregiver steps
   post 'care_giver_steps/skills_information', to: 'care_giver_steps#skills_information'
   post 'care_giver_steps/disease_management', to: 'care_giver_steps#conditions'
   post 'care_giver_steps/yes_no', to: 'care_giver_steps#yes_no'
   post 'care_giver_steps/personal_statement', to: 'care_giver_steps#personal_statement'
   post 'care_giver_steps/experience', to: 'care_giver_steps#experience'
   get 'states-cg', to: 'care_giver_steps#city'
   # family dashboard
   as :family do
      get 'family', to: 'family#index', as: :family_root
      get 'family/new_post', to: 'family#new_post'
      post 'family/create_post', to: 'family#create_post'
      post 'family/update_recipient_for_post', to: 'family#update_recipient_for_post'
      get 'family/my_posting', to: 'family#my_posting', as: :my_posting
      delete 'family/my_posting/delete/:id', to: 'family#delete_post', as: :delete_post
      get 'family/edit_posting', to: 'family#edit_posting', as: :edit_posting
      post 'family/update_post', to: 'family#update_post'
      get 'family/recipient', to: 'family#recipient'
      get 'family/edit_recipient/:id/edit', to: 'family#edit_recipient'
      patch 'family/update_recipient/:id', to: 'family#update_recipient'
      get 'family/team_search', to: 'family#team_search', as: :search_team
      get 'family/team_search_results', to: 'family#team_search_results', as: :search_team_results
      get 'family/team_search_results_state', to: 'family#team_search_results_state', as: :search_team_results_state
      get 'family/team_search_results_city', to: 'family#team_search_results_city', as: :search_team_results_city
      get 'family/team/:id', to: 'family#team_show', as: :team_show
      get 'family/team_member/:id', to: 'family#team_show_member', as: :team_show_member
      get 'family/team_selection/:id', to: 'family#team_selection', as: :team_selection
      get 'family/my_team/:id', to: 'family#my_team', as: :my_team
      patch 'family/remove_team', to: 'family#remove_team', as: :remove_team
   end
   # caregiver dashboard
   as :team do
      get 'team', to: 'team#index', as: :team_root
      get 'team/posts/:id', to: 'team#all_posts', as: :all_posts
      get 'team/my_team/:id', to: 'team#my_team', as: :my_care_team
      get 'team/remove_member/:id', to: 'team#remove_member', as: :remove_member
      get 'team/new_team', to: 'team#new_team'
      post 'team/create_team', to: 'team#create_team'
      get 'team/join_team', to: 'team#join_team', as: :join_teams
      get 'team/search_results', to: 'team#search_results', as: :team_results
      get 'team/search_results_state', to: 'team#search_results_state', as: :team_results_state
      get 'team/search_results_city', to: 'team#search_results_city', as: :team_results_city
      get 'team/edit_post/:id/edit', to: 'team#edit_post'
      patch 'team/edit_post/:id/update_post', to: 'team#update_post'
      get 'team/show_team/:id', to: 'team#show_team', as: :show_team
      get 'team/team_member/:id', to: 'team#show_member', as: :show_member
      patch '/team/update_team/:id', to: 'team#update_team'
      get 'team/hours/:id', to: 'team#hours', as: :care_hours
      post 'team/create_hours/:id', to: 'team#create_hours', as: :create_hours
      get 'team/leader_hours/:id', to: 'team#leader_hours', as: :leader_hours 
      get 'team/care_giver_hours/', to: 'team#care_giver_hours', as: :care_giver_hours 
      get 'team/edit_skills', to: 'team#edit_skills', as: :edit_skills 
      post 'team/edit_skills_update', to: 'team#edit_skills_update'
      get 'team/edit_disease', to: 'team#edit_disease', as: :edit_disease 
      post 'team/edit_disease_update', to: 'team#edit_disease_update'  
      get 'team/edit_questionnaire', to: 'team#edit_questionnaire', as: :edit_questionnaire
      post 'team/edit_questionnaire_update', to: 'team#edit_questionnaire_update'    
      get 'team/edit_experience', to: 'team#edit_experience', as: :edit_experience    
      patch 'team/edit_experience_update', to: 'team#edit_experience_update'
      get 'team/edit_statement', to: 'team#edit_statement', as: :edit_statement          
      post 'team/edit_statement_update', to: 'team#edit_statement_update'      
   end
end

app/views/layouts/partials/_contact.html.erb
<section class="home-contact-form">
   <div class="home-contact-form__text">
      <h1 style="color: #104A75">Send Us a Message</h1>
      <h4 class="image-about-paragraph__text">Service Support: 1-800-888-8888</h4>
      <h4 class="image-about-paragraph__text">Technical Support: 1-800-888-8888</h4>
   </div>
   <%= form_for @message, url: create_message_path do |f| %>
      <%= @message.errors.full_messages.join(', ') %>
      <div class="field">
         <%= f.text_field :name, placeholder: 'Name', class: 'signup-input-container--input' %>
      </div>
      <div class="field">
         <%= f.email_field :email, placeholder: 'Email', class: 'signup-input-container--input' %>
      </div>
      <div class="field">
         <%= f.text_area :body, placeholder: 'Message', class: 'signup-input-container--input', style: 'height: 250px !important' %>
      </div>
      <% if controller.action_name == "care_giver" %>
         <%= f.submit 'Send', class:'email-password__submit', style: 'background: #FFB052' %>
      <% else %>
         <%= f.submit 'Send', class:'email-password__submit', style: 'background: #104A75' %>
      <% end %>
   <% end %>
</section>

app/views/layouts/partials/_footer.html.erb
<footer>
   <div class="footer-container">
      <div class="footer-social-scroll">
         <div class="footer-social-scroll__social">
            <p class="footer-social-scroll__social--text">Follow Us!</p>
            <div class="footer-social-scroll__social--icons">
               <a href="#"><i class="fab fa-facebook"></i></a>
               <a href="#"><i class="fab fa-twitter-square"></i></a>
               <a href="#"><i class="fab fa-instagram"></i></a>
            </div>
         </div>
         <div class="footer-social-scroll__scroll">
            <p class="footer-social-scroll__scroll--text">Back to top</p>
            <i class="fas fa-arrow-circle-up"></i>
         </div>
      </div>
      <div class="footer-contact">
         <p class="footer-contact__text">Contact Us Now!</p>
         <p class="footer-contact__text">Service Support: 
            <a class="footer-contact__text--num" href="tel:+1-800-888-8888">1-800-888-8888</a>
         </p>
         <p class="footer-contact__text">Technical Support:
            <a class="footer-contact__text--num" href="tel:+1-800-888-8888">1-800-888-8888</a>
         </p>
      </div>
      <div class="footer-copyright">
         <small class="footer-copyright__text">©2018 TeamCarer. All Rights Reserved.</small>
      </div>
   </div>
</footer>

app/views/layouts/partials/_header.html.erb
<header>
   <div class="header-container">
      <div class="mobile-nav">
         <a style="display: flex;" href="/">
            <%= image_tag "logo.png", class: "mobile-nav__logo" %>
         </a>
         <a class="mobile-nav__lines toggle-nav">
            <span class="mobile-nav__lines--line1"></span>
            <span class="mobile-nav__lines--line2"></span>
            <span class="mobile-nav__lines--line3"></span>
         </a>
      </div>
      <nav class="desktop-nav">
         <ul class="desktop-nav-list">
            <% if family_signed_in? %>
               <a class="desktop-nav-list__item desktop-nav-list__item--text" style="margin-left: 120px;" href="/family/my_posting">Home</a>
               <li class="desktop-nav-list__item" style="margin-left: 18px;">Dashboard
                  <ul class="desktop-dropdown">
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/family/my_posting">Home</a>
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/family">My Profile</a>
                     <% unless current_family.job_post %>
                        <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/family">Create a Job Post</a>
                     <% end %>  
                     <% if current_family.care_team_id %>
                        <%= link_to "My Team", my_team_path(:id => current_family.care_team_id ), class: "desktop-dropdown__list-item desktop-dropdown__list-item--text" %>
                     <% end %>   
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/family/recipient">Care Recipient</a>   
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/family/team_search">Search For a Team</a>
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/families/edit">Settings</a>             
                  </ul>
               </li>
               <%= link_to "Log Out", destroy_family_session_path, method: :delete, class: "desktop-nav-list__item desktop-nav-list__item--text" %>
            <% elsif care_giver_signed_in? %>
               <a class="desktop-nav-list__item desktop-nav-list__item--text" style="margin-left: 120px;" href="/team">Home</a>
               <li class="desktop-nav-list__item" style="margin-left: 18px;">Dashboard
                  <ul class="desktop-dropdown">
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/team">Home</a>
                     <% if current_care_giver.care_team %>
                        <%= link_to "My team", my_care_team_path(:id => current_care_giver.care_team), :class => "desktop-dropdown__list-item desktop-dropdown__list-item--text" %>
                        <%= link_to "Job Postings", all_posts_path(:id => current_care_giver.id), class: "desktop-dropdown__list-item desktop-dropdown__list-item--text" %>
                     <% end %>
                     <% if current_care_giver.leader %>
                        <%= link_to "My team", my_care_team_path(:id => CareTeam.where(care_giver_id: current_care_giver.id)[0]), :class => "desktop-dropdown__list-item desktop-dropdown__list-item--text" %>
                        <%= link_to "Job Postings", all_posts_path(:id => current_care_giver.id), class: "desktop-dropdown__list-item desktop-dropdown__list-item--text" %>
                     <% end %>   
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/care_givers/edit">Settings</a>             
                  </ul>
               </li>
               <%= link_to "Log Out", destroy_care_giver_session_path, method: :delete, class: "desktop-nav-list__item desktop-nav-list__item--text" %>
            <% else %>
               <a class="desktop-nav-list__item desktop-nav-list__item--text" href="/">Home</a>
               <li class="desktop-nav-list__item">Log In 
                  <ul class="desktop-dropdown">
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/families/sign_in">Family</a>
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/care_givers/sign_in">Caregiver</a>
                  </ul>
               </li>
               <li class="desktop-nav-list__item">Sign Up 
                  <ul class="desktop-dropdown">
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/families/sign_up">Family</a>
                     <a class="desktop-dropdown__list-item desktop-dropdown__list-item--text" href="/care_givers/sign_up">Caregiver</a>
                  </ul>
               </li> 
               <a class="desktop-nav-list__item desktop-nav-list__item--text" id="aboutus" href="/">About Us</a>
               <a class="desktop-nav-list__item desktop-nav-list__item--text" id="contact" href="/">Contact</a>
            <% end %>
         </ul>
      </nav>
      <nav class="site-menu">
         <ul class="side-menu">
            <% if family_signed_in? %>
            <a class="side-menu__list-item side-menu__list-item--text" href="/family/my_posting">Home</a>
               <li class="side-menu__list-item">Dashboard <i class="fas fa-chevron-down"></i>
                  <ul class="sub-menu">
                     <%= link_to "- My Profile", "/family", class: "sub-menu__list-item sub-menu__list-item--text" %>
                     <% unless current_family.job_post %>
                        <%= link_to "- Create a Job Post", "/family", class: "sub-menu__list-item sub-menu__list-item--text" %>
                     <% end %>
                     <% if current_family.care_team_id %>
                        <%= link_to "- My Team", my_team_path(:id => current_family.care_team_id ), class: "sub-menu__list-item sub-menu__list-item--text" %>
                     <% end %>
                     <%= link_to "- Care Recipient", "/family/recipient", class: "sub-menu__list-item sub-menu__list-item--text" %>
                     <%= link_to "- Search For a Team", "/family/team_search", class: "sub-menu__list-item sub-menu__list-item--text" %>
                  </ul>
               </li>
               <%= link_to "Log Out", destroy_family_session_path, method: :delete, class: "side-menu__list-item side-menu__list-item--text" %>
               <%= link_to "Settings", "/families/edit", class: "side-menu__list-item side-menu__list-item--text" %>
               <li class="side-menu__list-item toggle-nav">Close</li>
            <% elsif care_giver_signed_in? %>
               <a class="side-menu__list-item side-menu__list-item--text" href="/team">Home</a>
               <% if current_care_giver.care_team %>
                  <li class="side-menu__list-item">Dashboard <i class="fas fa-chevron-down"></i>
                     <ul class="sub-menu">
                        <%= link_to "- Job Postings", all_posts_path(:id => current_care_giver.id), class: "sub-menu__list-item sub-menu__list-item--text" %>
                        <%= link_to "- My team", my_care_team_path(:id => current_care_giver.care_team), class: "sub-menu__list-item sub-menu__list-item--text" %>
                     </ul>
                  </li>
               <% end %>
               <% if current_care_giver.leader %>
                  <li class="side-menu__list-item">Dashboard <i class="fas fa-chevron-down"></i>
                     <ul class="sub-menu">
                        <%= link_to "- Job Postings", all_posts_path(:id => current_care_giver.id), class: "sub-menu__list-item sub-menu__list-item--text" %>
                        <%= link_to "- My team", my_care_team_path(:id => CareTeam.where(care_giver_id: current_care_giver.id)[0]), class: "sub-menu__list-item sub-menu__list-item--text" %>
                     </ul>
                  </li>
               <% end %>  
               <%= link_to "Log Out", destroy_care_giver_session_path, method: :delete, class: "side-menu__list-item side-menu__list-item--text" %>
               <%= link_to "Settings", "/care_givers/edit" , class: "side-menu__list-item side-menu__list-item--text" %>
               <li class="side-menu__list-item toggle-nav">Close</li>
            <% else %>
            <a class="side-menu__list-item side-menu__list-item--text" href="/">Home</a>
               <li class="side-menu__list-item">Sign Up <i class="fas fa-chevron-down"></i>
                  <ul class="sub-menu">
                     <a class="sub-menu__list-item sub-menu__list-item--text" href="/families/sign_up">- Family</a>
                     <a class="sub-menu__list-item sub-menu__list-item--text" href="/care_givers/sign_up" >- Caregiver</a>
                  </ul>
               </li>
               <li class="side-menu__list-item">Log In <i class="fas fa-chevron-down"></i>
                  <ul class="sub-menu">
                     <a class="sub-menu__list-item sub-menu__list-item--text" href="/families/sign_in">- Family</a>
                     <a class="sub-menu__list-item sub-menu__list-item--text" href="/care_givers/sign_in" >- Caregiver</a>
                  </ul>
               </li>
               <a class="side-menu__list-item side-menu__list-item--text" id="aboutus-mobile" href="/">About Us</a>
               <a class="side-menu__list-item side-menu__list-item--text" id="contact-mobile" href="/">Contact</a>
               <li class="side-menu__list-item toggle-nav">Close</li>
            <% end %>
         </ul>
      </nav>
   </div>
</header>

app/views/layouts/partials/_steps_header.html.erb
<header>
   <div class="header-container">
      <div class="mobile-nav">
         <%= image_tag "logo.png", class: "mobile-nav__logo" %>
      </div>
   </div>
</header>